version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:'gabalese'
      - POSTGRES_PASSWORD:'gabalese'
      - POSTGRES_DB:'database'
